version: "3.8"
services:
  web:
    image: ghcr.io/sicim69/assignment3-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: image: ghcr.io/sicim69/assignment3-redis:latest
    ports:
      - "6379:6379"
