name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Web Image
      run: |
        docker build -t ghcr.io/${{ github.actor }}/assignment3-web:latest ./web
        docker push ghcr.io/${{ github.actor }}/assignment3-web:latest


    - name: Pull, Tag, and Push Redis Image
      run: |
        docker pull redis:alpine
        docker tag redis:alpine ghcr.io/${{ github.actor }}/assignment3-redis:latest
        docker push ghcr.io/${{ github.actor }}/assignment3-redis:latest

